block_cipher = None
a = Analysis(['main.py'],
         pathex=['/Developer/PItests/minimal'],
         binaries=None,
         datas=[('image.png', '.'), ('config.json', '.')],
         hiddenimports=[utils, mappings, certifi, charset-normalizer, idna, python-dotenv, requests, urllib3, Pillow, websocket-client, loguru, beautifulsoup4, stem],
         hookspath=None,
         runtime_hooks=None,
         excludes=None,
         cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
         cipher=block_cipher)
